services:
  app:
    build: .
    container_name: gestor-activos-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-gestor_activos}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_key}
      - HASH_SERVICE_URL=http://hash-service:3010
    volumes:
      - ./mi-carpeta-imagenes:/app/mi-carpeta-imagenes
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gestor-activos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestor_activos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
